Watching for file changes with StatReloader
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2212
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
"GET / HTTP/1.1" 200 12068
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 12068
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2212
"GET / HTTP/1.1" 200 12068
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 79011
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 79011
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 79011
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 79011
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 79011
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'superadmin.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: superadmin.html
"GET / HTTP/1.1" 500 79101
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 78945
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 6, in home
    return render(request, 'index.html')  # Name of your frontend HTML file
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
"GET / HTTP/1.1" 500 78945
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 4324
"GET / HTTP/1.1" 200 0
"GET / HTTP/1.1" 200 4324
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 4339
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 4339
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 4339
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2313
Not Found: /
"GET / HTTP/1.1" 404 2313
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2313
Not Found: /
"GET / HTTP/1.1" 404 2313
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2313
Not Found: /login
"GET /login HTTP/1.1" 404 2346
Not Found: /signup
"GET /signup HTTP/1.1" 404 2349
Not Found: /index
"GET /index HTTP/1.1" 404 2346
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2313
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2476
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2476
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2521
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\forms.py", line 356, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 296, in get_select
    sql, params = self.compile(col)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 557, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\expressions.py", line 1309, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 548, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"POST / HTTP/1.1" 500 222741
"GET / HTTP/1.1" 200 3519
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2521
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\forms.py", line 356, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 296, in get_select
    sql, params = self.compile(col)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 557, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\expressions.py", line 1309, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 548, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"POST / HTTP/1.1" 500 222436
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\forms.py", line 356, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 296, in get_select
    sql, params = self.compile(col)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 557, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\expressions.py", line 1309, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 548, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"POST / HTTP/1.1" 500 222436
"GET / HTTP/1.1" 200 3519
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\forms.py", line 356, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 296, in get_select
    sql, params = self.compile(col)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 557, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\expressions.py", line 1309, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 548, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"POST / HTTP/1.1" 500 222436
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\forms.py", line 356, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 296, in get_select
    sql, params = self.compile(col)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 557, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\expressions.py", line 1309, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 548, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"POST / HTTP/1.1" 500 222388
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
"GET /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
"POST /accounts/signup/ HTTP/1.1" 200 3559
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 143, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\views.py", line 89, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\generic\edit.py", line 150, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 326, in full_clean
    self._clean_form()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\forms.py", line 342, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\forms.py", line 356, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\__init__.py", line 79, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 747, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
                                                            ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 296, in get_select
    sql, params = self.compile(col)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 557, in compile
    sql, params = node.as_sql(self, self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\expressions.py", line 1309, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 548, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
"POST / HTTP/1.1" 500 222368
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
"POST / HTTP/1.1" 200 3519
"POST / HTTP/1.1" 200 3519
- Broken pipe from ('127.0.0.1', 51038)
"POST / HTTP/1.1" 200 3519
Not Found: /superadmin
"GET /superadmin HTTP/1.1" 404 2518
Not Found: /accounts/superadmin
"GET /accounts/superadmin HTTP/1.1" 404 3181
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
- Broken pipe from ('127.0.0.1', 51039)
"POST / HTTP/1.1" 200 3519
"POST / HTTP/1.1" 200 3519
"POST / HTTP/1.1" 200 3519
"POST / HTTP/1.1" 200 3519
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3519
- Broken pipe from ('127.0.0.1', 51092)
"POST / HTTP/1.1" 200 3519
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 51136)
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 51137)
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2521
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
Not Found: /accounts/superadmin/
"GET /accounts/superadmin/ HTTP/1.1" 404 3184
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET /accounts/login/ HTTP/1.1" 200 3574
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET /accounts/login/ HTTP/1.1" 200 3574
"POST /accounts/login/ HTTP/1.1" 200 3574
"POST /accounts/login/ HTTP/1.1" 200 3574
"POST /accounts/login/ HTTP/1.1" 200 3574
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2521
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 200 3607
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
Not Found: /index
"GET /index HTTP/1.1" 404 2503
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4165
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
"GET /static/admin/css/login.css HTTP/1.1" 200 951
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
"GET /static/admin/css/base.css HTTP/1.1" 200 22092
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4324
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 4324
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
Not Found: /index
"GET /index HTTP/1.1" 404 2503
Not Found: /index/
"GET /index/ HTTP/1.1" 404 2506
Not Found: /superadmin/
"GET /superadmin/ HTTP/1.1" 404 2521
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 33, in signup_view
    user = User.objects.create_user(username=username, email=email, password=password1)
           ^^^^
NameError: name 'User' is not defined
"POST /accounts/signup/ HTTP/1.1" 500 67914
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 53575)
- Broken pipe from ('127.0.0.1', 53577)
"GET / HTTP/1.1" 200 3574
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2521
Watching for file changes with StatReloader
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 30, in signup_view
    return HttpResponse("Passwords do not match!")
           ^^^^^^^^^^^^
NameError: name 'HttpResponse' is not defined
"POST /accounts/signup/ HTTP/1.1" 500 67964
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 53838)
- Broken pipe from ('127.0.0.1', 53840)
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 30, in signup_view
    return HttpResponse("Passwords do not match!")
           ^^^^^^^^^^^^
NameError: name 'HttpResponse' is not defined
"POST /accounts/signup/ HTTP/1.1" 500 67964
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /accounts/signup/ HTTP/1.1" 200 23
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 200 23
"GET /accounts/signup/ HTTP/1.1" 200 3607
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 34, in signup_view
    user = User.objects.create_user(username=username, email=email, password=password1)
           ^^^^
NameError: name 'User' is not defined
"POST /accounts/signup/ HTTP/1.1" 500 67866
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /accounts/signup/ HTTP/1.1" 200 23
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 01:48:50.172777+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3175
"GET /accounts/index/ HTTP/1.1" 200 4339
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 01:53:43.925725+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
"GET /accounts/index/ HTTP/1.1" 200 4339
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 54032)
- Broken pipe from ('127.0.0.1', 54035)
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:02:55.375182+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 54039)
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:03:23.082807+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
User 'ram' (User) logged in at 2024-11-22 02:03:35.126445+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Not Found: /accounts/profile/
"GET /accounts/profile/ HTTP/1.1" 404 3332
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:10:01.789892+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 302 0
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/index/ HTTP/1.1" 200 4339
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 54079)
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:11:13.989974+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:12:28.971113+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 35, in signup_view
    user = User.objects.create_user(username=username, email=email, password=password1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\models.py", line 162, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\models.py", line 156, in _create_user
    user.save(using=self._db)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
"POST /accounts/signup/ HTTP/1.1" 500 169282
"GET /accounts/signup/ HTTP/1.1" 200 3607
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 35, in signup_view
    user = User.objects.create_user(username=username, email=email, password=password1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\models.py", line 162, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\models.py", line 156, in _create_user
    user.save(using=self._db)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
"POST /accounts/signup/ HTTP/1.1" 500 169362
"POST /accounts/signup/ HTTP/1.1" 200 23
"GET /accounts/signup/ HTTP/1.1" 200 3607
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: auth_user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py", line 35, in signup_view
    user = User.objects.create_user(username=username, email=email, password=password1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\models.py", line 162, in create_user
    return self._create_user(username, email, password, **extra_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\models.py", line 156, in _create_user
    user.save(using=self._db)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\base_user.py", line 62, in save
    super().save(*args, **kwargs)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: auth_user.username
"POST /accounts/signup/ HTTP/1.1" 500 169414
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:18:08.371281+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 54125)
User 'ram' (User) logged in at 2024-11-22 02:18:08.933658+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:19:00.676102+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET / HTTP/1.1" 200 3574
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/base.css HTTP/1.1" 200 22092
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
"GET /static/admin/css/login.css HTTP/1.1" 200 951
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
"GET /static/admin/js/theme.js HTTP/1.1" 200 1653
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 3836
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '87' (User) logged in at 2024-11-22 02:21:04.043432+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET /accounts/index/? HTTP/1.1" 200 4339
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 54198)
- Broken pipe from ('127.0.0.1', 54196)
"GET / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:27:56.650360+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"POST /admin/login/?next=/admin/ HTTP/1.1" 200 3836
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
User 'Suyog' (Admin) logged in at 2024-11-22 02:34:10.909358+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 54227)
User 'Suyog' (Admin) logged in at 2024-11-22 02:34:12.607168+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5857
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Not Found: /login/
"GET /login/ HTTP/1.1" 404 2663
Not Found: /login
"GET /login HTTP/1.1" 404 2660
Not Found: /login
"GET /login HTTP/1.1" 404 2660
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 54251)
- Broken pipe from ('127.0.0.1', 54254)
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET / HTTP/1.1" 200 3574
"GET /admin/ HTTP/1.1" 200 5857
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
- Broken pipe from ('127.0.0.1', 54261)
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
"GET /admin/auth/user/add/ HTTP/1.1" 200 11309
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/forms.css HTTP/1.1" 200 8710
"GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/actions.js HTTP/1.1" 200 8076
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /accounts/signup/ HTTP/1.1" 200 3607
Not Found: /login
"GET /login HTTP/1.1" 404 2660
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-22 02:40:49.540384+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2503
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET / HTTP/1.1" 200 3574
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"GET / HTTP/1.1" 200 3574
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
User 'Suyog' (Admin) logged in at 2024-11-22 02:43:56.606440+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5857
"GET / HTTP/1.1" 200 3574
"GET /admin/auth/group/add/ HTTP/1.1" 200 11164
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15502
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /admin/auth/user/add/ HTTP/1.1" 200 11309
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/ HTTP/1.1" 200 5877
"GET /admin/ HTTP/1.1" 200 5857
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User 'lana' (User) logged in at 2024-11-22 02:45:37.489571+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET / HTTP/1.1" 200 3574
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 54321)
- Broken pipe from ('127.0.0.1', 54324)
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-22 02:51:51.168287+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
"GET /admin/ HTTP/1.1" 200 5857
"GET /admin/auth/user/ HTTP/1.1" 200 13786
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"POST /admin/logout/ HTTP/1.1" 200 3560
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4165
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User 'test' (User) logged in at 2024-11-22 02:55:06.332434+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4339
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2678
"POST / HTTP/1.1" 200 3574
- Broken pipe from ('127.0.0.1', 57168)
- Broken pipe from ('127.0.0.1', 57169)
- Broken pipe from ('127.0.0.1', 57170)
- Broken pipe from ('127.0.0.1', 57171)
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-25 12:51:52.908918+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4336
"GET /accounts/index/? HTTP/1.1" 200 4336
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"GET /static/admin/css/login.css HTTP/1.1" 200 951
User 'Suyog' (Admin) logged in at 2024-11-25 12:52:38.383782+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5857
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/auth/group/ HTTP/1.1" 200 7491
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/actions.js HTTP/1.1" 200 8076
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/auth/user/ HTTP/1.1" 200 14235
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
Watching for file changes with StatReloader
C:\Users\gaura\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User 'ram' (User) logged in at 2024-11-25 14:42:01.943899+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6013
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-25 15:58:06.201996+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6013
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '324' (User) logged in at 2024-11-25 15:59:15.482664+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6285
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"GET /static/admin/css/login.css HTTP/1.1" 200 951
User 'Suyog' (Admin) logged in at 2024-11-25 15:59:40.325096+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 5857
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /admin/auth/user/ HTTP/1.1" 200 14677
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9097
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/actions.js HTTP/1.1" 200 8076
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
"POST /admin/auth/user/ HTTP/1.1" 200 7973
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/cancel.js HTTP/1.1" 200 884
"POST /admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 11652
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /accounts/index/ HTTP/1.1" 200 4320
"GET /accounts/index/? HTTP/1.1" 200 4320
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '123' (User) logged in at 2024-11-25 16:12:04.710477+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4591
"GET /admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/auth/user/ HTTP/1.1" 200 3697
"GET /static/admin/css/login.css HTTP/1.1" 304 0
User 'Suyog' (Admin) logged in at 2024-11-25 16:12:19.670652+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/auth/user/ HTTP/1.1" 302 0
"GET /admin/auth/user/ HTTP/1.1" 200 11960
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-25 16:34:50.930535+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4589
"GET /accounts/index/ HTTP/1.1" 200 4685
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /accounts/index/ HTTP/1.1" 200 4928
"GET /accounts/index/ HTTP/1.1" 200 4756
"GET /accounts/index/ HTTP/1.1" 200 4718
"GET /accounts/index/ HTTP/1.1" 200 4725
"GET /accounts/index/ HTTP/1.1" 200 4735
"GET /accounts/index/ HTTP/1.1" 200 4751
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
"GET / HTTP/1.1" 200 3574
User '324' (User) logged in at 2024-11-25 16:46:50.668922+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4751
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-25 16:57:33.754559+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 4751
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '432' (User) logged in at 2024-11-25 16:58:41.929777+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User '432' (User) logged in at 2024-11-25 16:59:46.337725+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2835
User 'Suyog' (Admin) logged in at 2024-11-26 01:40:14.769501+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5022
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 01:45:44.178385+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5201
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '987' (User) logged in at 2024-11-26 01:46:48.395461+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
"POST / HTTP/1.1" 200 3574
User '987' (User) logged in at 2024-11-26 01:48:15.141612+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5517
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 3677
"GET /static/admin/css/login.css HTTP/1.1" 304 0
User 'Suyog' (Admin) logged in at 2024-11-26 01:48:47.176116+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 7988
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /admin/auth/group/ HTTP/1.1" 200 7491
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /admin/auth/user/ HTTP/1.1" 200 12847
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET /admin/ HTTP/1.1" 200 8807
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 8577
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 8577
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 8577
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 13469
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 8577
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 8577
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/ HTTP/1.1" 200 8807
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 01:56:26.671430+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 11384
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 13469
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:01.674161+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:11.518603+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:32.424177+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59338)
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:34.148292+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59339)
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:35.075402+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59340)
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:35.408064+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:03:43.340299+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
"GET /admin/auth/user/5/change/ HTTP/1.1" 200 22191
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/forms.css HTTP/1.1" 200 8794
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15502
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11564
"GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /admin/auth/user/5/password/ HTTP/1.1" 200 8904
"GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
"GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
"POST /admin/auth/user/5/password/ HTTP/1.1" 302 0
"GET /admin/auth/user/5/change/ HTTP/1.1" 200 22327
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
User 'Suyog' (Admin) logged in at 2024-11-26 02:05:03.080790+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:07.076689+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:19.608630+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59348)
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:20.615820+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59349)
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:21.642371+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59350)
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:22.212267+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59351)
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:22.390207+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59352)
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:22.524425+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59353)
User 'Suyog' (Admin) logged in at 2024-11-26 02:06:22.640520+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:08:40.665621+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:08:50.262498+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59354)
User 'Suyog' (Admin) logged in at 2024-11-26 02:08:51.704128+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
- Broken pipe from ('127.0.0.1', 59357)
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2503
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:12:51.880727+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:13:58.149083+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
"POST / HTTP/1.1" 200 3574
User '123' (User) logged in at 2024-11-26 02:14:33.675528+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6322
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4165
User 'Suyog' (Admin) logged in at 2024-11-26 02:15:05.583288+00:00 from IP: 127.0.0.1
- Broken pipe from ('127.0.0.1', 59368)
User 'Suyog' (Admin) logged in at 2024-11-26 02:15:06.607771+00:00 from IP: 127.0.0.1
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 9149
"GET /admin/auth/user/5/change/ HTTP/1.1" 200 22191
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 13469
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Watching for file changes with StatReloader
Forbidden (CSRF token from POST incorrect.): /
"POST / HTTP/1.1" 403 2503
"GET /accounts/logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:19:08.397698+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6322
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 02:22:06.346139+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6322
"GET /accounts/index/ HTTP/1.1" 200 6184
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 05:16:54.177694+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6185
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 31703
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 06:15:31.087551+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6179
"GET /admin/ HTTP/1.1" 200 9148
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 32400
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/auth/user/ HTTP/1.1" 200 13468
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 07:08:50.527077+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6185
"GET /accounts/index/ HTTP/1.1" 200 6217
"GET /accounts/index/ HTTP/1.1" 200 5892
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 07:28:52.026145+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5891
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User 'we' (User) logged in at 2024-11-26 09:53:25.311221+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-26 09:53:32.874906+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5730
"GET /admin/ HTTP/1.1" 200 9148
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
"GET /admin/auth/group/ HTTP/1.1" 200 8112
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /admin/auth/user/ HTTP/1.1" 200 13908
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
"GET /admin/login_history/ HTTP/1.1" 200 5241
"GET /admin/auth/user/ HTTP/1.1" 200 13908
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 35261
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2835
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '234' (User) logged in at 2024-11-27 01:40:12.411173+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-27 01:40:23.178592+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5979
"GET /admin/ HTTP/1.1" 200 9148
"GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-27 02:27:16.591615+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5979
Not Found: /admmin
"GET /admmin HTTP/1.1" 404 2820
"GET /admin/ HTTP/1.1" 200 8329
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\Job_Portal\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-27 02:37:01.351584+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 5979
"GET /admin/ HTTP/1.1" 200 9148
"GET /admin/auth/user/ HTTP/1.1" 200 14350
"GET /static/admin/css/changelists.css HTTP/1.1" 304 0
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
"GET /static/admin/js/actions.js HTTP/1.1" 304 0
"GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
"GET /static/admin/js/urlify.js HTTP/1.1" 304 0
"GET /static/admin/js/core.js HTTP/1.1" 304 0
"GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
"GET /static/admin/img/search.svg HTTP/1.1" 304 0
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-no.svg HTTP/1.1" 304 0
"GET /static/admin/js/filters.js HTTP/1.1" 304 0
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 304 0
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 37422
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User 'manoj' (User) logged in at 2024-11-27 02:41:49.768585+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-27 02:41:59.938447+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6236
"GET /admin/ HTTP/1.1" 200 9148
"GET /admin/auth/user/ HTTP/1.1" 200 14802
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 38887
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
"GET /accounts/signup/ HTTP/1.1" 200 3607
"POST /accounts/signup/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 3574
User '435' (User) logged in at 2024-11-27 04:04:34.231062+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
Forbidden: /accounts/index/
"GET /accounts/index/ HTTP/1.1" 403 43
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-27 04:04:45.123021+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6493
"GET /admin/ HTTP/1.1" 200 9148
"GET /admin/login_history/loginhistory/ HTTP/1.1" 200 40346
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 3574
User 'Suyog' (Admin) logged in at 2024-11-27 04:16:46.838177+00:00 from IP: 127.0.0.1
"POST / HTTP/1.1" 302 0
"GET /accounts/index/ HTTP/1.1" 200 6494
"GET /admin/ HTTP/1.1" 200 9148
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\ACER\Desktop\LOG\Job_Portal\accounts\views.py changed, reloading.
Watching for file changes with StatReloader
